name: Compile documents

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies via apt
      run: sudo apt install -y texlive-latex-extra texlive-science latexmk curl

    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Make all documents
      run: make

    - name: Stash documents
      run: |
        mkdir $HOME/docs
        mv **/*.pdf $HOME/docs

    - name: Checkout gh-actions-builds branch
      uses: actions/checkout@v1
      with:
        ref: gh-pages

    - name: Commit reports
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name = "GitHub Action"
        rm -rf docs
        mv $HOME/docs $(pwd)
        git add docs
        git commit -m "Add changes"

